server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@your_db_alias_medium?TNS_ADMIN=C:/path/to/wallet
    username: your_db_user
    password: your_db_password
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
